### ISSUE TITLE
libvips supports bitdepth: 2

### ISSUE THREAD

**Issue by noraj** [noraj/PixelChart#1]
https://github.com/libvips/ruby-vips/issues/230#issuecomment-649432902

`libvips` 8.10 will support 1, 2 and 4 bit PNG, so we will be able to have smaller image size

Just need to use `bitdepth: 1` when generating the output. https://github.com/noraj/PixelChart/blob/cbf30aa8d63b6285df3f7847171e6ef24c567025/lib/pixelchart.rb#L134

**Comment by Nakilon** [comment]
Excuse me, isn't "2 colors" a "1 bit depth"?

**Comment by noraj** [comment]
@Nakilon Right !
